[package]
name = "q"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5"
env_logger = "0.11.8"
log = "0.4.27"
tptp = "0.31.1"

[lib]
name = "qlib"
path = "src/lib.rs"

[[bin]]
name = "qprover"
path = "src/main.rs"


